/*
   Copyright 2025 Dmytro Minochkin

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package cloud.dmytrominochkin.ai.llamacompose.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF6B5E10)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF6E388)
val onPrimaryContainerLight = Color(0xFF524700)
val secondaryLight = Color(0xFF655F40)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEDE3BC)
val onSecondaryContainerLight = Color(0xFF4D472B)
val tertiaryLight = Color(0xFF426650)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC4ECD0)
val onTertiaryContainerLight = Color(0xFF2B4E39)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF9EC)
val onBackgroundLight = Color(0xFF1E1C13)
val surfaceLight = Color(0xFFFFF9EC)
val onSurfaceLight = Color(0xFF1E1C13)
val surfaceVariantLight = Color(0xFFE9E2D0)
val onSurfaceVariantLight = Color(0xFF4A4739)
val outlineLight = Color(0xFF7C7768)
val outlineVariantLight = Color(0xFFCCC6B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF333027)
val inverseOnSurfaceLight = Color(0xFFF7F0E2)
val inversePrimaryLight = Color(0xFFD9C76F)
val surfaceDimLight = Color(0xFFDFDACC)
val surfaceBrightLight = Color(0xFFFFF9EC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF9F3E5)
val surfaceContainerLight = Color(0xFFF4EDDF)
val surfaceContainerHighLight = Color(0xFFEEE8DA)
val surfaceContainerHighestLight = Color(0xFFE8E2D4)

val primaryLightMediumContrast = Color(0xFF3F3600)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF7B6D1F)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF3C361C)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF746D4E)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF193D29)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF51755E)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF9EC)
val onBackgroundLightMediumContrast = Color(0xFF1E1C13)
val surfaceLightMediumContrast = Color(0xFFFFF9EC)
val onSurfaceLightMediumContrast = Color(0xFF131109)
val surfaceVariantLightMediumContrast = Color(0xFFE9E2D0)
val onSurfaceVariantLightMediumContrast = Color(0xFF393629)
val outlineLightMediumContrast = Color(0xFF565244)
val outlineVariantLightMediumContrast = Color(0xFF716D5E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF333027)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF7F0E2)
val inversePrimaryLightMediumContrast = Color(0xFFD9C76F)
val surfaceDimLightMediumContrast = Color(0xFFCCC6B9)
val surfaceBrightLightMediumContrast = Color(0xFFFFF9EC)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF9F3E5)
val surfaceContainerLightMediumContrast = Color(0xFFEEE8DA)
val surfaceContainerHighLightMediumContrast = Color(0xFFE2DCCF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD7D1C4)

val primaryLightHighContrast = Color(0xFF342C00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF544900)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF312C12)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF4F492D)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF0E3320)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2D503B)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF9EC)
val onBackgroundLightHighContrast = Color(0xFF1E1C13)
val surfaceLightHighContrast = Color(0xFFFFF9EC)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE9E2D0)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2F2C20)
val outlineVariantLightHighContrast = Color(0xFF4D493C)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF333027)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFD9C76F)
val surfaceDimLightHighContrast = Color(0xFFBEB8AC)
val surfaceBrightLightHighContrast = Color(0xFFFFF9EC)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF7F0E2)
val surfaceContainerLightHighContrast = Color(0xFFE8E2D4)
val surfaceContainerHighLightHighContrast = Color(0xFFDAD4C7)
val surfaceContainerHighestLightHighContrast = Color(0xFFCCC6B9)

val primaryDark = Color(0xFFD9C76F)
val onPrimaryDark = Color(0xFF383000)
val primaryContainerDark = Color(0xFF524700)
val onPrimaryContainerDark = Color(0xFFF6E388)
val secondaryDark = Color(0xFFD0C7A2)
val onSecondaryDark = Color(0xFF363016)
val secondaryContainerDark = Color(0xFF4D472B)
val onSecondaryContainerDark = Color(0xFFEDE3BC)
val tertiaryDark = Color(0xFFA8D0B4)
val onTertiaryDark = Color(0xFF133724)
val tertiaryContainerDark = Color(0xFF2B4E39)
val onTertiaryContainerDark = Color(0xFFC4ECD0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF15130C)
val onBackgroundDark = Color(0xFFE8E2D4)
val surfaceDark = Color(0xFF15130C)
val onSurfaceDark = Color(0xFFE8E2D4)
val surfaceVariantDark = Color(0xFF4A4739)
val onSurfaceVariantDark = Color(0xFFCCC6B4)
val outlineDark = Color(0xFF969180)
val outlineVariantDark = Color(0xFF4A4739)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE8E2D4)
val inverseOnSurfaceDark = Color(0xFF333027)
val inversePrimaryDark = Color(0xFF6B5E10)
val surfaceDimDark = Color(0xFF15130C)
val surfaceBrightDark = Color(0xFF3C3930)
val surfaceContainerLowestDark = Color(0xFF100E07)
val surfaceContainerLowDark = Color(0xFF1E1C13)
val surfaceContainerDark = Color(0xFF222017)
val surfaceContainerHighDark = Color(0xFF2C2A21)
val surfaceContainerHighestDark = Color(0xFF37352B)

val primaryDarkMediumContrast = Color(0xFFEFDD83)
val onPrimaryDarkMediumContrast = Color(0xFF2C2600)
val primaryContainerDarkMediumContrast = Color(0xFFA09140)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFE6DCB6)
val onSecondaryDarkMediumContrast = Color(0xFF2B260D)
val secondaryContainerDarkMediumContrast = Color(0xFF99916F)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFBEE6CA)
val onTertiaryDarkMediumContrast = Color(0xFF062C1A)
val tertiaryContainerDarkMediumContrast = Color(0xFF749980)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF15130C)
val onBackgroundDarkMediumContrast = Color(0xFFE8E2D4)
val surfaceDarkMediumContrast = Color(0xFF15130C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4A4739)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE3DCCA)
val outlineDarkMediumContrast = Color(0xFFB7B2A0)
val outlineVariantDarkMediumContrast = Color(0xFF959080)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE8E2D4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2C2A21)
val inversePrimaryDarkMediumContrast = Color(0xFF534800)
val surfaceDimDarkMediumContrast = Color(0xFF15130C)
val surfaceBrightDarkMediumContrast = Color(0xFF47443B)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090703)
val surfaceContainerLowDarkMediumContrast = Color(0xFF201E15)
val surfaceContainerDarkMediumContrast = Color(0xFF2A281F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF353329)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF403E34)

val primaryDarkHighContrast = Color(0xFFFFF0B1)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD5C36C)
val onPrimaryContainerDarkHighContrast = Color(0xFF0E0B00)
val secondaryDarkHighContrast = Color(0xFFFBF0C9)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFCCC39E)
val onSecondaryContainerDarkHighContrast = Color(0xFF0E0B00)
val tertiaryDarkHighContrast = Color(0xFFD1FADD)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFA4CCB1)
val onTertiaryContainerDarkHighContrast = Color(0xFF000E05)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF15130C)
val onBackgroundDarkHighContrast = Color(0xFFE8E2D4)
val surfaceDarkHighContrast = Color(0xFF15130C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4A4739)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF7F0DD)
val outlineVariantDarkHighContrast = Color(0xFFC9C2B1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE8E2D4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF534800)
val surfaceDimDarkHighContrast = Color(0xFF15130C)
val surfaceBrightDarkHighContrast = Color(0xFF535046)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF222017)
val surfaceContainerDarkHighContrast = Color(0xFF333027)
val surfaceContainerHighDarkHighContrast = Color(0xFF3E3B32)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4A473D)







